### ISSUE TITLE
Experience analysts 

### ISSUE THREAD

**Issue by Azizadx** [Azizadx/user_analytics_in_the_telecommunication#22]
#### Task 4. 1 - Aggregate, per customer, the following information (treat missing & outliers by replacing by the mean or the mode of the corresponding variable):

  - [x] Average TCP retransmission
  - [x] Average RTT
  - [x] Handset type
  - [x] Average throughput

#### Task 4.2 - Compute & list 10 of the top, bottom and most frequent:

  - [x] TCP values in the dataset. 
  - [x] RTT values in the dataset.
  - [x] Throughput values in the dataset.

#### Task 4.3 - Compute & report:

  - [x] The distribution of the average throughput per handset type and provide interpretation for your findings.
  - [x] The average TCP retransmission view per handset type and provide interpretation for your findings.

#### Task 4.4 - Using the experience metrics above, perform a k-means clustering (where k = 3) to segment users into groups of experiences and provide a brief description of each cluster. (The description must define each group based on your understanding of the data)
